spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver


logging:
  level:
    p6spy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.jdbc.core: TRACE
    # 패키지 전체
    com.ai.hybridsearch.service: DEBUG
    org.springframework.context: DEBUG
    org.springframework.boot.context.properties: DEBUG

langchain:
  model-type: ${MODEL_TYPE}
  target-dimensions: ${TARGET_DIMENSIONS}
  openai:
    api-key: ${OPENAI_API_KEY}
    model: text-embedding-3-small
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: embedding-001
  embedding:
    model: all-minilm-l6-v2